Books/Books/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Books.Models
{
    public class Author
    {
        public int AuthorID { get; set; }
        public string FullName { get; set; }
        public DateTime Birthday { get; set; }
        public string Biography { get; set; }
    }
}

Books/Books/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Books.Models;
using Books.ViewModels;

namespace Books.Controllers
{
    public class AuthorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Author
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        //// GET: Author/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Author author = db.Authors.Find(id);
        //    if (author == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(author);
        //}

        // GET: Author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,FullName,Birthday,Biography")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorID,FullName,Birthday,Biography")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Author/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            AuthorPageContent apc = new AuthorPageContent();
            apc.Author = db.Authors.Find(id);
            apc.AuthorsBooks = db.Books.Where(i => i.AuthorId == apc.Author.AuthorID).OrderByDescending(p => p.PublishDate).ToList();

            return View(apc);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Books/Books/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Books.Models;
using Books.Repositories;
using System.IO;
using System.Data.Entity.Infrastructure;
namespace Books.Controllers
{
    public class BookController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Book_EF_Repository _booksRepository { get; set; }
        private Book_EF_Repository booksRepository
        {
            get
            {
                if (_booksRepository == null)
                    _booksRepository = new Book_EF_Repository();
                return _booksRepository;
            }
        }
        // GET: Book
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.Author).Include(b => b.Publisher);
            return View(booksRepository.Get());
            
        }

        // GET: Book/Details/5
        public ActionResult Details(int id)
        {
            Book book = booksRepository.Get(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(db.Authors, "AuthorID", "FullName");
            ViewBag.PublisherId = new SelectList(db.Publishers, "PublisherID", "PublisherName");
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookId,Name,AuthorId,PageCount,UnitPrice,Details,PublishDate,UnitsInStock,IsActive,TotalSell,PublisherId,Image,ImageFile")] Book book)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(book.ImageFile.FileName);
                string extension = Path.GetExtension(book.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                book.Image = "../Image/" + fileName;
                fileName = Path.Combine(Server.MapPath("../Image/"), fileName);
                book.ImageFile.SaveAs(fileName);
                ModelState.Clear();
                booksRepository.Add(book);
                return RedirectToAction("Index");
            }

            ViewBag.AuthorId = new SelectList(db.Authors, "AuthorID", "FullName", book.AuthorId);
            ViewBag.PublisherId = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherId);
            //string fileName = Path.GetFileNameWithoutExtension(book.ImageFile.FileName);
            //string extension = Path.GetExtension(book.ImageFile.FileName);
            //fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            //book.Image = "../Image/" + fileName;
            //fileName = Path.Combine(Server.MapPath("../Image/"),fileName);
            //book.ImageFile.SaveAs(fileName);
            //ModelState.Clear();
            return View(book);
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int id)
        {
            Book book = booksRepository.Get(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorId = new SelectList(db.Authors, "AuthorID", "FullName", book.AuthorId);
            ViewBag.PublisherId = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherId);
            return View(book);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookId,Name,AuthorId,PageCount,UnitPrice,Details,PublishDate,UnitsInStock,IsActive,TotalSell,PublisherId")] Book book)
        {
            if (ModelState.IsValid)
            {
                booksRepository.Update(book);
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Authors, "AuthorID", "FullName", book.AuthorId);
            ViewBag.PublisherId = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherId);
            return View(book);
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int id)
        {
            Book book = booksRepository.Get(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = booksRepository.Get(id);
            booksRepository.Remove(book);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Books/Books/Views/Author/Create.cshtml
@model Books.Models.Author

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Biography, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Biography, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Biography, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Books/Books/Views/Author/Delete.cshtml
@model Books.Models.Author

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Author</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Biography)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Biography)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Books/Books/Views/Author/Details.cshtml
@model Books.ViewModels.AuthorPageContent
@using Books.Models
@{
    ViewBag.Title = "Details";
}
@foreach (Book item in Model.AuthorsBook)
{
    @*<h1>@item.Author.FullName</h1>
        <h3>Kitap ismi:@item.Name</h3>
        <h3>Yayımlanma Tarihi:@item.PublishDate</h3>
        <h3>Sayfa sayısı:@item.PageCount</h3>
        <h3>Toplam satış:@item.TotalSell</h3>*@
    @*<table class="table bg-light position-relative">
            <tr>
                <th>
                    Yazar ismi
                </th>
                <th>
                    Kitap İsmi
                </th>
                <th>
                    Yayımlanma Tarihi
                </th>
                <th>
                    Sayfa sayısı
                </th>
                <th>
                    Toplam satış
                </th>
            </tr>
            <tr>
                <td>
                    @item.Author.FullName
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.PublishDate
                </td>
                <td>
                    @item.PageCount
                </td>
                <td>
                    @item.TotalSell
                </td>
            </tr>
        </table>*@
}
<h1>About Author</h1>

@*<div>
        <h4>Author</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Birthday)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Birthday)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Biography)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Biography)
            </dd>

        </dl>
    </div>*@


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
    body {
        font-size: 1.4rem;
    }

    .img {
        border-radius: 50%;
        width: 100px;
    }

    .arkaPlan {
        opacity: 0.8;
        width: 100%;
        position: absolute;
        left: 0;
        top: 0;
        height: auto;
    }
</style>


<div>
    <img src="https://foodtank.com/wp-content/uploads/2021/07/alfons-morales-YLSwjSy7stw-unsplash.jpg" alt="background" class="arkaPlan">
</div>
<div class="container">

    <div class="row mt-5">
        <div class="bg-light position-relative pt-2 m-0 rounded-pill">
            <nav aria-label="breadcrumb ">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Ana Sayfa", "Index", "Home")</a></li>
                    <li class="breadcrumb-item text-center">@Html.ActionLink("Yazarlar", "Index", "Author")</li>
                    <li class="breadcrumb-item active" aria-current="page">@Html.ActionLink(Model.author.FullName, "Details", "Author")</li>
                </ol>
            </nav>
        </div>
        <div class="col-md-2 mt-2">
            <div class="card bg-light" style="width: 18rem;">
                <div class="box-content text-center rounded-3 bg-light">
                    <!-- <div class="w-100 text-black bg-opacity-50 bg-warning ribbon-container">
                        <h3>Yazar Hakkında</h3>
                    </div>                    -->
                    <!-- https://picsum.photos/200 -->
                    <img src="https://www.cumhuriyet.com.tr/Archive/2018/10/11/1108090_resource/15.jpg" class="card-img-top " alt="...">
                    <div class="card-body bg-light">
                        <h2 class="card-title "><strong>@Model.author.FullName</strong></h2>
                        <hr />
                        <p class="card-text">@Model.author.Biography </p>
                        <p>@Model.author.Birthday.Year-@Model.author.Birthday.Month-@Model.author.Birthday.Day</p>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-10 mt-2 bg-white">

            <table class="tab-content table table-bordered table-responsive table-striped position-relative">
                <tr>
                    <th>
                        Book Name
                    </th>
                    <th>
                        Publish Date
                    </th>
                    <th>
                        Page Count
                    </th>
                    <th>
                        Total Sell
                    </th>
                    <th>
                        Units In Stock
                    </th>
                    <th>
                        Unit Price
                    </th>
                </tr>
                @foreach (Book book in Model.AuthorsBook)
                {
                    <tr>

                        <td>
                            @book.Name
                        </td>
                        <td>
                            @book.PublishDate.Year-@book.PublishDate.Month-@book.PublishDate.Day
                        </td>
                        <td>
                            @book.PageCount
                        </td>
                        <td>
                            @book.TotalSell
                        </td>
                        <td>
                            @book.UnitsInStock
                        </td>
                        <td>
                            @book.UnitPrice
                        </td>
                        <td>
                            @*@Html.ActionLink("Edit", "Edit", new { id = Model.author.AuthorID }) |*@
                            @Html.ActionLink("Edit", "Edit", "Book", new { id = book.BookId }) |
                            @Html.ActionLink("Back to List", "Index")
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.author.AuthorID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Books/Books/Views/Author/Edit.cshtml
@model Books.Models.Author

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AuthorID)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Biography, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Biography, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Biography, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Books/Books/Views/Author/Index.cshtml
@model IEnumerable<Books.Models.Author>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Biography)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Biography)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AuthorID }) |
            @Html.ActionLink("Details", "Details", new { id=item.AuthorID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AuthorID })
        </td>
    </tr>
}

</table>